import fs from "node:fs";
import path from "node:path";
import { parse } from "csv-parse/sync";
import {
  analysisDashboardPath,
  comparisonCacheDir,
  comparisonDashboardPath,
} from "./simArtifacts.js";

/**
 * Extracts the structured content (sections, stat cards, Plotly figure
 * payloads, player-explorer data) out of the self-contained HTML dashboards
 * written by vendor/progbox_cpp/tools/analysis.py `_render_html`.
 *
 * The HTML is machine-generated by a single writer with stable markers, so
 * plain regexes are sufficient and keep us dependency-free. If upstream
 * re-vendoring ever changes the markers, extraction throws
 * MarkersNotFoundError and callers fall back to the raw-HTML iframe view.
 */

export class MarkersNotFoundError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "MarkersNotFoundError";
  }
}

export interface PlotlyFigureJson {
  data: unknown[];
  layout: Record<string, unknown>;
  config?: Record<string, unknown>;
}

export type ChartRef =
  | { kind: "figure"; payloadId: string; minHeight: number }
  | { kind: "player-explorer" };

export interface ExtractedSection {
  id: string;
  title: string;
  intro: string;
  charts: ChartRef[];
}

export interface StatCard {
  label: string;
  value: string;
  color: string | null;
}

export interface ExtractedDashboard {
  schemaVersion: 1;
  hero: { title: string; subtitle: string };
  statCards: StatCard[];
  sections: ExtractedSection[];
  /** Plotly figure JSON keyed by payload id ("payload-1", ...). */
  figures: Record<string, PlotlyFigureJson>;
  /** Parsed explorer-data payload (single-run dashboards only). */
  playerExplorer: unknown | null;
}

const SCHEMA_VERSION = 1 as const;

// `_fig_to_payload` escapes "</" as "<\/" inside the JSON, so a lazy match
// can never terminate at an embedded "</script>" and JSON.parse works on the
// raw text (\/ is a legal JSON escape).
const PAYLOAD_RE =
  /<script type="application\/json" id="(payload-\d+|explorer-data)">([\s\S]*?)<\/script>/g;

const SECTION_RE =
  /<section id="([^"]+)" class="section">\s*<h2 class="section-title">([\s\S]*?)<\/h2>\s*<p class="section-intro">([\s\S]*?)<\/p>([\s\S]*?)<\/section>/g;

const CHART_HOST_RE = /data-src="(payload-\d+)"[^>]*min-height:(\d+)px/g;

const STAT_CARD_RE =
  /<div class="stat-card"><div class="lbl">([\s\S]*?)<\/div><div class="val"(?: style="color:([^"]+)")?>([\s\S]*?)<\/div><\/div>/g;

const HERO_RE = /<div class="hero">\s*<h1>([\s\S]*?)<\/h1>\s*<p>([\s\S]*?)<\/p>/;

const FOOTER_SUBTITLE_RE =
  /<time[^>]*>[^<]*<\/time>\s*&middot;\s*([\s\S]*?)\s*<\/div>/;

export function extractDashboard(html: string): ExtractedDashboard {
  const figures: Record<string, PlotlyFigureJson> = {};
  let playerExplorer: unknown | null = null;

  for (const m of html.matchAll(PAYLOAD_RE)) {
    const [, id, body] = m;
    let parsed: unknown;
    try {
      parsed = JSON.parse(body);
    } catch (e) {
      throw new MarkersNotFoundError(
        `Failed to parse embedded JSON payload "${id}": ${e instanceof Error ? e.message : e}`,
      );
    }
    if (id === "explorer-data") {
      playerExplorer = parsed;
    } else {
      figures[id] = parsed as PlotlyFigureJson;
    }
  }

  if (Object.keys(figures).length === 0) {
    // Fallback-engine HTML (analysisGenerate.ts) has none of these markers.
    throw new MarkersNotFoundError(
      "No Plotly figure payloads found in dashboard HTML",
    );
  }

  const sections: ExtractedSection[] = [];
  for (const m of html.matchAll(SECTION_RE)) {
    const [, id, title, intro, body] = m;
    const charts: ChartRef[] = [];
    // Chart hosts and the explorer widget appear in source order inside the
    // section body; payload scripts live at the end of the document, so
    // data-src is the only reliable figure<->section mapping.
    const markers: { index: number; ref: ChartRef }[] = [];
    for (const host of body.matchAll(CHART_HOST_RE)) {
      markers.push({
        index: host.index ?? 0,
        ref: {
          kind: "figure",
          payloadId: host[1],
          minHeight: Number(host[2]),
        },
      });
    }
    const explorerIdx = body.indexOf('id="explorer-data"');
    if (explorerIdx !== -1) {
      markers.push({ index: explorerIdx, ref: { kind: "player-explorer" } });
    }
    markers.sort((a, b) => a.index - b.index);
    charts.push(...markers.map((m2) => m2.ref));
    sections.push({
      id,
      title: title.trim(),
      intro: intro.trim(),
      charts,
    });
  }

  if (sections.length === 0) {
    throw new MarkersNotFoundError("No sections found in dashboard HTML");
  }

  const statCards: StatCard[] = [];
  for (const m of html.matchAll(STAT_CARD_RE)) {
    const [, label, color, value] = m;
    statCards.push({
      label: label.trim(),
      value: value.trim(),
      color: color ?? null,
    });
  }

  const heroMatch = HERO_RE.exec(html);
  const subtitleMatch = FOOTER_SUBTITLE_RE.exec(html);

  return {
    schemaVersion: SCHEMA_VERSION,
    hero: {
      title: heroMatch?.[1]?.trim() ?? "",
      subtitle: subtitleMatch?.[1]?.trim() ?? heroMatch?.[2]?.trim() ?? "",
    },
    statCards,
    sections,
    figures,
    playerExplorer,
  };
}

// CACHED WRAPPERS -----------------------------------------------------------

export function analysisPayloadsPath(build: string): string {
  return path.join(path.dirname(analysisDashboardPath(build)), "analysis_payloads.json");
}

export function comparisonPayloadsPath(key: string): string {
  return path.join(comparisonCacheDir(key), "comparison_payloads.json");
}

export function comparisonScorecardPath(key: string): string {
  return path.join(comparisonCacheDir(key), "comparison_scorecard.csv");
}

function extractWithCache(htmlPath: string, cachePath: string): ExtractedDashboard {
  const htmlStat = fs.statSync(htmlPath);
  if (fs.existsSync(cachePath)) {
    try {
      const cacheStat = fs.statSync(cachePath);
      if (cacheStat.mtimeMs >= htmlStat.mtimeMs) {
        const cached = JSON.parse(fs.readFileSync(cachePath, "utf8")) as ExtractedDashboard;
        if (cached.schemaVersion === SCHEMA_VERSION) return cached;
      }
    } catch {
      // Corrupt/unreadable cache: fall through and re-extract.
    }
  }
  const extracted = extractDashboard(fs.readFileSync(htmlPath, "utf8"));
  const tmp = `${cachePath}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify(extracted), "utf8");
  fs.renameSync(tmp, cachePath);
  return extracted;
}

/** Extract (with on-disk cache) the single-run dashboard for a build. */
export function getAnalysisData(build: string): ExtractedDashboard {
  return extractWithCache(analysisDashboardPath(build), analysisPayloadsPath(build));
}

/** Extract (with on-disk cache) a cached comparison dashboard by cache key. */
export function getComparisonData(key: string): ExtractedDashboard {
  return extractWithCache(comparisonDashboardPath(key), comparisonPayloadsPath(key));
}

// SCORECARD -----------------------------------------------------------------

// Mirrors SCRIPT_PALETTE in vendor/progbox_cpp/tools/analysis.py:193-201 —
// one distinct color per progression script, assigned in run order.
export const SCRIPT_PALETTE = [
  "#2563eb",
  "#dc2626",
  "#16a34a",
  "#f97316",
  "#7c3aed",
  "#0891b2",
  "#be185d",
  "#65a30d",
] as const;

export interface ParsedScorecard {
  /** Script labels, in run order (column order of the native table). */
  scripts: string[];
  /** SCRIPT_PALETTE color per script, matching the overlay chart colors. */
  colors: string[];
  /** One entry per metric row; values align with `scripts`. */
  metrics: { name: string; values: (number | null)[] }[];
}

/** Parse comparison_scorecard.csv (rows = scripts, columns = metrics). */
export function parseScorecardCsv(csvText: string): ParsedScorecard {
  const rows = parse(csvText, {
    columns: true,
    skip_empty_lines: true,
  }) as Record<string, string>[];
  const scripts = rows.map((r) => r.Script ?? "");
  const colors = rows.map((_, i) => SCRIPT_PALETTE[i % SCRIPT_PALETTE.length]);
  const metricNames =
    rows.length > 0 ? Object.keys(rows[0]).filter((c) => c !== "Script") : [];
  const metrics = metricNames.map((name) => ({
    name,
    values: rows.map((r) => {
      const v = r[name];
      if (v === undefined || v === "") return null;
      const n = Number(v);
      return Number.isFinite(n) ? n : null;
    }),
  }));
  return { scripts, colors, metrics };
}

/** Read + parse the cached scorecard CSV for a comparison, or null if absent. */
export function getComparisonScorecard(key: string): ParsedScorecard | null {
  const p = comparisonScorecardPath(key);
  if (!fs.existsSync(p)) return null;
  try {
    return parseScorecardCsv(fs.readFileSync(p, "utf8"));
  } catch {
    return null;
  }
}
